"""
Backward-compatible re-exports from digest_pipeline.

All production logic lives in digest_pipeline.py — this module preserves
the historical `import digest` surface so existing tests and tooling
keep working without changes.
"""

from digest_pipeline import (
    AD_MARKERS,
    CHANNELS_FILE,
    CHUNK_DELAY_SECONDS,
    COMMON_WORDS,
    FIRST_RUN_LOOKBACK_HOURS,
    MAX_DELIVERED_CHUNKS,
    MAX_DELIVERED_IDS,
    MAX_MODEL_INPUT_CHARS,
    MAX_MODEL_POST_CHARS,
    MAX_PREVIEW_CHARS,
    MAX_RECENT_NEWS,
    MAX_RECENT_NEWS_CHARS,
    MIN_TEXT_LENGTH,
    MODELS,
    PERM_TIMEZONE,
    PROMO_PATTERNS,
    RECENT_NEWS_HISTORY_BATCH,
    RECENT_NEWS_HOURS,
    RETRY_ATTEMPTS,
    STATE_FILE,
    URL_RE,
    WORD_RE,
    DigestPipeline,
    ad_ids_from_response,
    ad_review_prompt,
    analysis_text,
    are_duplicate_candidates,
    candidate_clusters,
    chunk_checkpoint_id,
    collect_posts,
    comparison_tokens,
    cross_run_semantic_deduplicate,
    duplicate_ids_from_response,
    duplicate_prompt,
    extract_json_object,
    extract_urls,
    filter_and_deduplicate,
    format_digest,
    format_post_time,
    generate_json,
    has_ad_marker,
    is_probable_ad,
    is_suspicious_ad,
    load_channels,
    load_state,
    main,
    make_ai_batches,
    make_source_url,
    model_item,
    normalize_text,
    parse_datetime,
    recent_news_prompt,
    recent_news_repeat_ids,
    require_environment,
    replay_hours_from_environment,
    review_suspicious_ads,
    save_state,
    semantic_deduplicate,
    semantic_deduplication_pass,
    send_telegram_message,
    telegram_chunks,
    utc_now,
)
